import Head from "next/head"
import {
  FaebookIcon,
  LinkedInIcon,
  GoogleIcon,
  InstagramIcon,
  HopeIcon,
} from "../../components/icons"
import Link from "next/link"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='h-screen flex flex-col justify-center items-start gap-[40px] relative w-[1920px] '>
        <section
          id='loginSection'
          className='w-[436px] h-[602px] absolute left-[262px] top-[234px]'
        >
          <div id='logo' className='gap-x-2 flex w-[162px] h-[43px]'>
            <HopeIcon />
            <p className='font-Inter text-[#232D42] font-normal text-2xl non-italic'>
              Hope Ui
            </p>
          </div>
          <div
            id='content'
            className='flex flex-col justify-center items-center p-0 gap-4 w-[436px] order-none'
          >
            <form id='signIn form' className='h-[391px]  contents'>
              <div className='w-[197px] h-[87px] text-center'>
                <div className=' h-[43px] font-semibold text-2xl'>Sign In</div>
                <p className='text-md font-normal text-[#8A92A6]'>
                  Sign in to stay connected.
                </p>
              </div>
              <div
                id='form'
                className='gap-6 order-1 w-[436px] h-[288px] p-0 flex flex-col justify-center'
              >
                <div className='gap-2 h-20 contents'>
                  <div>
                    <label className='w-[41px] h-7 leading-3' htmlFor='email'>
                      Email
                    </label>
                    <br />
                    <input
                      id='email'
                      className='w-full h-10 px-2 py-1 border border-solid border-[#3A57EB] rounded focus:border-[#3A57EB] focus:outline-none'
                      type={"email"}
                    />
                  </div>
                  <div>
                    <label
                      className='w-[41px] h-7 leading-3'
                      htmlFor='password'
                    >
                      Password
                    </label>
                    <br />
                    <input
                      id='password'
                      className='w-full h-10 border px-2 py-1 border-solid border-[#3A57EB] rounded focus:border-[#3A57EB] focus:outline-none'
                      type={"password"}
                    />
                  </div>
                  <div className='h-7 flex flex-row mt-2 gap-[166px]'>
                    <span className='flex flex-row gap-2'>
                      <input type={"checkbox"} />
                      <p>Remember Me</p>
                    </span>

                    <a href='#' className='text-[#3A57EB] '>
                      Forgot Password
                    </a>
                  </div>
                  <button className='bg-[#3A57EB] w-[188px] mx-auto px-6 py-2 text-white rounded border'>
                    Sign In
                  </button>
                </div>
              </div>
            </form>
          </div>

          <div className='gap-4 contents text-center'>
            <p className='font-normal text-sm leading-7'>
              or sing in with othe accounts?
            </p>
            <div className='justify-center flex gap-2'>
              <a href=''>
                <GoogleIcon />
              </a>
              <a href=''>
                <FaebookIcon />
              </a>
              <a href=''>
                <InstagramIcon />
              </a>
              <a href=''>
                <LinkedInIcon />
              </a>
            </div>
            <div className='justify-center flex gap-6'>
              <p>Don't have an account?</p>
              <Link href={"/signUp"}>
                <p className='text-[#3A57EB]'>Click here to sign up.</p>
              </Link>
            </div>
          </div>
        </section>
        <section id='BackgroundImage'>
          <img
            src='/BackgroundImage.jpg'
            className='h-screen w-1/2 right-0 top-0 absolute'
          />
        </section>
      </div>
    </>
  )
}
